import Nav from "./(components)/Nav";
import "./globals.css";
import { Inter } from "next/font/google";
import SessionProvider from "./(components)/SessionProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ticketing-app",
  description: "Generated by Kristian Kenjeres",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className="flex flex-col h-screen max-h-screen">
            <Nav />
            <main className="flex-grow overflow-y-auto bg-page text-default-text">
              {children}
            </main>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
